name: "Lint"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Ruff
        run: uv tool install ruff

      - name: Check code style with Ruff
        run: uv tool run ruff check --output-format=github .

      - name: Check formatting with Ruff
        run: uv tool run ruff format --check .
